module.exports = {
  extends: [
    "eslint:recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
  ],
  plugins: ["import"],
  parserOptions: {
    ecmaVersion: 2019,
    sourceType: "module",
  },
  env: {
    es6: true,
    commonjs: true,
  },
  rules: {
    "array-callback-return": "error",
    "class-methods-use-this": "error",
    "default-param-last": "error",
    eqeqeq: "error",
    "import/first": "error",
    "import/no-extraneous-dependencies": [
      "error",
      { devDependencies: ["test/**/*"] },
    ],
    "import/order": [
      "error",
      { alphabetize: { order: "asc", caseInsensitive: true } },
    ],
    "no-await-in-loop": "error",
    "no-caller": "error",
    "no-eval": "error",
    "no-implied-eval": "error",
    "no-invalid-this": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-promise-executor-return": "error",
    "no-sequences": "error",
    "no-template-curly-in-string": "error",
    "no-unused-vars": ["error", { vars: "local", args: "none" }],
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "sort-imports": ["error", { ignoreDeclarationSort: true }],
    radix: "error",
  },
};
